server:
  port: 8888
#  maxHttpHeaderSize: 8192

spring:
  datasource:
    url: jdbc:mysql://rm-bp10toc7t373skida9o.mysql.rds.aliyuncs.com:3306/jinju_db?useUnicode=true&characterEncoding=utf8
    username: root
    password: geeklab20*
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    hibernate:
      show-sql: true
  redis:
    host: 47.100.177.183
    port: 8936

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true


# 七牛
qiniu:
  accessKey: 19aQdu9aO5mtERdtAo4kQyUsYB6KOPVdE8ukMaBh
  secretKey: NM0gE2uPl0syJnJ7-JPuSVyXryq03YNY_ujvHQd4
  jinju-bucket: jinju
  meiwen-bucket: meiwen
  jinjuDomainName: http://p2g5cb64g.bkt.clouddn.com/
  meiwenDomainName: http://p2wuhp1bg.bkt.clouddn.com/

jinju:
  defaultPhotoUrl: http://p2g5cb64g.bkt.clouddn.com/FqzcOdtAM96-Fe3ssizwDpMVCbiD


logging:
  level:
    org:
      springframework: WARN
    spring:
      springboot:
        dao: DEBUG

#spring.redis.host=192.168.22.221
#spring.redis.port=6379

